### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by lesbianlizard** [theolizard/remote-numpad-server#2]
I tried to run the numpad server in Sway, but it fails to start due to `DISPLAY` being unset:
```
% java -jar Remote.Numpad.Server-1.5.2-all.jar
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:165)
        at java.desktop/java.awt.Window.<init>(Window.java:545)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
        at com.guillaumepayet.remotenumpadserver.ui.StatusWindow.<init>(StatusWindow.kt:35)
        at com.guillaumepayet.remotenumpadserver.MainKt$main$1.invokeSuspend(main.kt:46)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.guillaumepayet.remotenumpadserver.MainKt.main(main.kt:37)
        at com.guillaumepayet.remotenumpadserver.MainKt.main(main.kt)
```

I also tried running it using xwayland, in which case the GUI appears functional, but none of the generated keypresses actually reach running wayland applications, or even other X apps running in xwayland.

It looks like the logic for generating keypresses happens in `KeyEventProcessor.kt` and `VirtualNumpad.kt`, which are both using the AWT library which is generating the exception about `DISPLAY` being unset. From a quick search, I wasn't able to find much clear information about whether this library has any wayland support at all, but given its age, I suppose it doesn't.

In any case, I'd love to be able to use this application on my wayland system, but it doesn't appear possible right now.

**Comment by guillaumevpayet** [comment]
Hi, thank you for the feedback.

This app uses Java and I think that is not really compatible with Wayland.

I am going to release a native server for linux that uses something more recent and modern than Java. It will be compatible with Wayland.

Stay tuned!

**Comment by guillaumevpayet** [comment]
I am trying to sunset the server program in favour of the HID connection (the default, now named "Bluetooth", in the Android app). Please try to use the HID connection and open new issues on the main remote-numpad GitHub page.
